# Generated by Django 6.0.6 on 2026-07-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="age_rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age_rating", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="directors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("director", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="films",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=1000)),
                ("poster", models.CharField(max_length=300)),
                ("trailer", models.CharField(max_length=300)),
                ("year_of_release", models.PositiveSmallIntegerField(max_length=4)),
                ("runtime", models.CharField(max_length=100)),
                ("age_ratingID", models.PositiveSmallIntegerField(max_length=10)),
                ("genreID", models.PositiveSmallIntegerField(max_length=2)),
                ("directorID", models.PositiveSmallIntegerField(max_length=4)),
                ("actors", models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name="genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="tvshows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=1000)),
                ("poster", models.CharField(max_length=300)),
                ("trailer", models.CharField(max_length=300)),
                ("year_of_release", models.PositiveSmallIntegerField(max_length=4)),
                ("number_of_seasons", models.PositiveSmallIntegerField(max_length=2)),
                ("age_ratingID", models.PositiveSmallIntegerField(max_length=10)),
                ("genreID", models.PositiveSmallIntegerField(max_length=2)),
                ("directorID", models.PositiveSmallIntegerField(max_length=4)),
                ("actors", models.CharField(max_length=600)),
            ],
        ),
    ]
