# Generated by Django 6.0.6 on 2026-08-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="directors",
        ),
        migrations.RemoveField(
            model_name="films",
            name="age_ratingID",
        ),
        migrations.RemoveField(
            model_name="films",
            name="directorID",
        ),
        migrations.RemoveField(
            model_name="films",
            name="genreID",
        ),
        migrations.RemoveField(
            model_name="films",
            name="year_of_release",
        ),
        migrations.RemoveField(
            model_name="tvshows",
            name="age_ratingID",
        ),
        migrations.RemoveField(
            model_name="tvshows",
            name="directorID",
        ),
        migrations.RemoveField(
            model_name="tvshows",
            name="genreID",
        ),
        migrations.RemoveField(
            model_name="tvshows",
            name="number_of_seasons",
        ),
        migrations.RemoveField(
            model_name="tvshows",
            name="year_of_release",
        ),
        migrations.AddField(
            model_name="films",
            name="director",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="tvshows",
            name="director",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="films",
            name="poster",
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name="films",
            name="trailer",
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name="tvshows",
            name="poster",
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name="tvshows",
            name="trailer",
            field=models.URLField(max_length=300),
        ),
    ]
