# Generated by Django 6.0.6 on 2026-08-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_delete_directors_remove_films_age_ratingid_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="tvshows",
            new_name="tv_shows",
        ),
    ]
