# Generated by Django 6.0.6 on 2026-08-06 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0003_rename_tvshows_tv_shows"),
    ]

    operations = [
        migrations.AddField(
            model_name="films",
            name="age_rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="media.age_rating",
            ),
        ),
        migrations.AddField(
            model_name="films",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="media.genre",
            ),
        ),
        migrations.AddField(
            model_name="films",
            name="year_of_release",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tv_shows",
            name="age_rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="media.age_rating",
            ),
        ),
        migrations.AddField(
            model_name="tv_shows",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="media.genre",
            ),
        ),
        migrations.AddField(
            model_name="tv_shows",
            name="number_of_seasons",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tv_shows",
            name="year_of_release",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
