# Generated by Django 6.0.6 on 2026-08-06 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0004_films_age_rating_films_genre_films_year_of_release_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="films",
            old_name="name",
            new_name="films",
        ),
        migrations.RenameField(
            model_name="tv_shows",
            old_name="name",
            new_name="tv_shows",
        ),
    ]
