# Generated by Django 6.0.6 on 2026-08-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0005_rename_name_films_films_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tv_shows",
            name="number_of_seasons",
            field=models.CharField(max_length=3, null=True),
        ),
    ]
