# Generated by Django 6.0.6 on 2026-08-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0006_alter_tv_shows_number_of_seasons"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=70)),
                ("last_name", models.CharField(max_length=70)),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=15)),
            ],
        ),
    ]
