# Generated by Django 6.0.6 on 2026-08-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0007_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
